version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install make
          command: apk add make
      - run:
          name: Build docker image
          command: make build
      - run:
          name: Convert notebooks to html
          command: make html
      - store_artifacts:
          path: dist
          destination: notebooks